### ISSUE TITLE
Watchers breaking computed property

### ISSUE THREAD

**Issue by paulschwoerer** [meteor-vue/vue-meteor-tracker#38] opened 2018-08-14 09:06 UTC
I might have found an issue when using watchers on computed properties including meteor data.
To illustrate, take the following example (using the VueMeteor demo app):

In the Notes.vue Component we'll be adding a watcher for the `firstNote()` computed property.
```js
watch: {
  firstNote(val) {
    console.log(val)
  }
}
```

After adding the watcher, the computed property will not compute, as `this.notes` is undefined in the computed property for some reason.

The same can be observed for another another example:

```js
computed: {
  notesCount() {
    return this.notes ? this.notes.length : -1;
  }
}
```
This computed property will compute just fine, but as soon as we add a watcher to observe changes in the item count, it will break, meaning it will not recompute and always show -1.

```js
watch: {
  notesCount(value) {
    console.log(value)
  }
}
```

This behavior can be fixed with the following:

```js
computed: {
  notesCount() {
    return this.$subReady.notes ? this.notes.length : -1;
  }
}
```

Using this computed property, the code will behave as expected, updating the count of items and printing it to the console through the watcher whenever it changes.
Maybe this is something to look into as I think the first example should behave in the same way as the latter.

This issue might be related to #34.

Reproducing example repo https://github.com/paulschwoerer/meteor-vue-tracker-watcher-error-example

Cheers!

**Comment by thearabbit** [comment] 2018-09-06 00:16
+1, I can't use `watch`

**Comment by hluz** [comment] 2018-09-07 00:14
Maybe try this?

```   
meteor: {
    $subscribe: {
      ['app.company']: [],
    },
    company() {
      return Company.findOne() || {}
    },
  },
watch:{
   company:{
      handler(val){
           // don't work
      },
      immediate: true,
   }
}
```

**Comment by dylanalizon** [comment] 2018-09-10 15:38
Maybe we have to use observeChanges ? But how ? Someone has an idea please ?

**Comment by thearabbit** [comment] 2018-09-10 23:18
I will try soon

**Comment by mathieustan** [comment] 2018-09-20 13:06
I encounter the same problem. It seems like when watcher remove computed reactivity. 
If I comment a watch, which are linked to a Meteor data, computed works fine.

Exemple with watch : 
```
computed: { 
	notes() {
		return this.$autorun(() => Notes.find({}).fetch());
	}, 
	notesCount() {
		console.log(this.notes); // always undefined
		return this.notes.length;
	},
},
watch: {
	notesCount(count) {
		console.log(count); // undefined
	}
}
```

Exemple WITHOUT watch : 
```
computed: { 
	notes() {
		return this.$autorun(() => Notes.find({}).fetch());
	}, 
	notesCount() {
		console.log(this.notes); // return a number, works fine & reactive
		return this.notes.length;
	},
},
watch: {
	/*notesCount(count) {
		console.log(count); // undefined
	}*/
}
```

**Comment by mathieustan** [comment] 2018-09-21 12:57
I investigate this issue. 
It seems like, in _computedWatchers, our computed property looses its deps. 

With just a computed property : 
<img width="408" alt="capture d ecran 2018-09-21 a 14 54 16" src="https://user-images.githubusercontent.com/38033090/45882446-7d5ce800-bdae-11e8-88ce-d4be9196d5f4.png">

When there is a watch on this computed property: 
<img width="267" alt="capture d ecran 2018-09-21 a 14 53 52" src="https://user-images.githubusercontent.com/38033090/45882485-95cd0280-bdae-11e8-9461-87360bb7eb29.png">

**Comment by vblagomir** [comment] 2018-10-02 10:05
+1

**Comment by Akryum** [comment] 2018-10-09 13:59
Duplicate of #34

**Closed by Akryum** 2018-10-09 13:59 UTC
