### ISSUE TITLE
`Watcher` don't work?

### ISSUE THREAD

**Issue by thearabbit** [meteor-vue/vue-meteor-tracker#41] opened 2018-09-06 00:23 UTC
```js
meteor: {
    $subscribe: {
      ['app.company']: [],
    },
    company() {
      return Company.findOne()
    },
  },
watch:{
   company:{
      handler(val){
           // don't work
      },
      immediate: true,
   }
}
```

**Comment by mizzao** [comment] 2018-09-11 17:42
I think this is the same as what I reported in #34

**Comment by Akryum** [comment] 2018-10-09 13:59
Duplicate of #34

**Closed by Akryum** 2018-10-09 13:59 UTC
